import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { renderPiExtension } from "./pi-extension-template.ts";

export interface GeneratedFileResult {
  path: string;
  status: "created" | "unchanged" | "preserved";
}

function displayPath(filePath: string): string {
  return filePath.replaceAll("\\", "/");
}

async function writeGeneratedFile(absolutePath: string, reportedPath: string, content: string): Promise<GeneratedFileResult> {
  await mkdir(path.dirname(absolutePath), { recursive: true });
  const display = displayPath(reportedPath);
  try {
    const existing = await readFile(absolutePath, "utf8");
    if (existing === content) return { path: display, status: "unchanged" };
    return { path: display, status: "preserved" };
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  await writeFile(absolutePath, content, "utf8");
  return { path: display, status: "created" };
}

function mcpConfigJson(): string {
  return `${JSON.stringify({
    mcpServers: {
      "spec-guard": {
        command: "npx",
        args: ["spec-guard-mcp"],
        env: {}
      }
    }
  }, null, 2)}\n`;
}

function genericSnippetJson(): string {
  return `${JSON.stringify({
    command: "npx",
    args: ["spec-guard-mcp"],
    note: "Runs the Spec Guard MCP stdio server via the locally-installed spec-guard-mcp bin (npx resolves node_modules/.bin first). Tools call shared core actions directly; they do not shell out to the CLI."
  }, null, 2)}\n`;
}

export const AGENT_GUIDE_RULES = [
  "Use Spec Guard tools directly.",
  "Call status/quickstart first.",
  "Do not substitute CLI for MCP except bootstrap/init.",
  "Do not inspect Spec Guard package/source internals for workflow parameters.",
  "Human-confirmed fields require actual human responses.",
  "Human-approved content is canonical intent.",
  "Discuss is non-mutating.",
  "Binary gates remain Yes/No/Discuss after discussion.",
  "Fixed binary decisions record option 1 or 2 only.",
  "Custom non-binary choices require numbered confirmation.",
  "NEVER box the human into your generated buttons. EVERY work.choice / work.choices records `options_presented` (the options you ACTUALLY showed), and it MUST include — as VISIBLE numbered options, not the dialog's easy-to-miss 'Other' — BOTH a 'Type your own answer' option AND a 'Discuss' option. Present every structural choice like: 1. <option A>, 2. <option B>, 3. Type your own answer, 4. Discuss. The gate REJECTS a choice that omits either (WORK_CHOICE_OPTIONS_INCOMPLETE), so you must re-ask with them. Discuss is non-mutating (deliberation, nothing recorded); a typed answer is recorded as the human's actual response.",
  "Choose ORIGINATION + TARGET up front at work.create. ORIGINATION: modify_existing INHERITS an existing app's platform/architecture/stack (makes NO structural choices); new_entirely ESTABLISHES them for a brand-new project; new_in_existing adds a NEW app inside an existing repo (establishes ITS OWN baseline, leaves sibling apps untouched) — it REQUIRES a fresh, explicit, non-default target_id (a target that has no accepted baseline yet; if the target already exists, use modify_existing). TARGET: a Work Packet runs in exactly ONE app — pass target_id (the app's id) so the dev-runtime/build gates are scoped to THAT app, not the whole repo. modify_existing INHERITS the named target's already-PROVEN runtime baseline via work.target.attach (no re-proving); new_entirely / new_in_existing ESTABLISH the target's baseline as post-authorization bootstrap. Single-app repos may omit target_id (a reserved default target is used). Call baseline.list to discover existing targets + their accepted/draft status before choosing.",
  "RUNTIME-LESS work is first-class: pure docs, cross-cutting edits, or writing tests that ship NO runnable code set target_id = null — no runtime baseline, no dev-runtime/build gates, but the full approval/authorize/complete lifecycle still applies. Policed in three layers: (1) a runtime-relevant classification (reusable_api / rest_api / reusable_ui / one_off_application_ui) or an app platform CANNOT be runtime-less — it's rejected (RUNTIME_TARGET_REQUIRED), pass a target_id instead; (2) a null-target packet that isn't purely operational_document needs a human-approved runtime_not_relevant_reason recorded at work.create (it's bound into the approval hash); (3) a runtime-less packet whose ACTUAL changed files include executable source is rejected at completion (RUNTIME_LESS_CONTRADICTED_BY_DIFF) — declare a target_id for code work.",
  "THE MODEL: one Work Packet is ONE aggregate document (.spec-guard/packets/<id>.json) holding embedded Specs. A fresh packet (work.create) IS its own single Spec; work.decompose splits it into >=2 homogeneous Specs (the Specs ARE the breakdown — there is no separate Plan artifact). The human's ENTIRE interaction is THREE whole-Work-Packet gates: work.approve -> work.authorize -> work.complete; the agent does all per-Spec drafting + implementation in between and never stops the human per Spec.",
  "Order: inspect status/config (mcp.status, config.check); work.create the packet + choose its origination; flesh out the whole-WP intent with work.intent (desired outcomes, in/out of scope, users, edge cases, open questions — work.create seeds only the goal); (new_entirely) choose the high-level platform, then the structural architecture, then separately the framework/tooling stack — BEFORE drafting acceptance criteria; once the human has picked all three, record them in ONE work.choices call (batch) rather than three work.choice calls (the per-axis CHOOSING stays separate; only the recording is batched); if the work spans multiple surfaces/classifications, work.decompose it into homogeneous Specs; PER Spec: (UI) resolve the mockup question FIRST (work.spec.mockup), draft + validate the ACs (work.spec.acs — tag each AC's classification; greenfield Specs need a bootstrap AC), set the implementation plan (work.spec.plan); THEN — ONCE EVERY Spec is drafted + planned — record the INDEPENDENT pre-approval reviews (work.review): per-Spec (with spec_id, spawned in PARALLEL) and/or one whole-WP review (no spec_id), so every Spec ends up covered by a passing review, PLUS — for a multi-Spec packet — a whole-WP COHERENCE review over ALL Specs together (no spec_id, independent of every author); (modify_existing) inherit the target's already-proven baseline via work.target.attach BEFORE approval; the ONE bulk whole-WP approval (work.approve — every Spec's ACs + scope + docs + structural decisions, reviewed together); whole-WP authorize (work.authorize — greenlights every Spec to build; write NO product code before this); PER Spec drive the role loop (work.spec.record / work.spec.advance: implementer -> validator -> focused reviewer -> fixer); (new_entirely / new_in_existing) establish + PROVE the target's runtime baseline as bootstrap work after authorization; then the human completion gate (work.complete).",
  "The whole-Work-Packet INTENT is the human's request that everything else serves: work.create captures only the goal, so flesh out the rest with work.intent — desired_outcomes (what the work MUST achieve), in_scope / out_of_scope, users_actors, edge_cases, open_questions. The bulk approval is BLOCKED until ALL SIX intent sections are populated (INTENT_INCOMPLETE): desired_outcomes, in_scope, out_of_scope, users_actors, edge_cases, open_questions — if a section genuinely has nothing, record that explicitly (e.g. open_questions: ['none — requirements are settled']) rather than leaving it empty. The intent is in the whole-WP approval hash, so editing it after approval re-stales it.",
  "Architecture and stack are DISTINCT work.choice gates: architecture is structural shape, stack is framework/tooling. Generate options appropriate to the platform and work for each; Spec Guard provides no fixed option list. They are chosen BEFORE the acceptance criteria so the ACs reflect them. Each is a SEPARATE genuine human choice — do NOT infer one from another or record a partial free-form answer as confirmed; re-prompt for the un-chosen parts. For a NEW application UI (one_off_application_ui) the stack work.choice MUST present the component/UI-library as a genuine choice and record it in option_details.component_library ('none' is a valid recorded value) — the stack choice is REJECTED (WORK_CHOICE_UI_STACK_COMPONENT_LIBRARY_REQUIRED) without it. A reusable UI library, an API surface, or a feature on an existing app does NOT require it.",
  "There is NO separate human AC-approval prompt. Draft + validate each Spec's acceptance criteria with work.spec.acs; the human reviews + approves them together with everything else in the ONE bulk whole-WP approval (work.approve), whose hash covers every Spec's ACs. So a UI mockup's ACs are still human-approved — at the bulk gate, with the Viewer showing them — not in a separate prompt.",
  "Packet APPROVAL (work.approve) and implementation AUTHORIZATION (work.authorize) are TWO SEPARATE human decisions — do NOT bundle them into one 'approve and I'll start building' prompt. At the approval gate present exactly these options to the human: (1) Approve the work packet only [work.approve Yes, then STOP — the human can authorize separately/later], (2) Approve AND authorize implementation [work.approve Yes, then work.authorize Yes — proceed to build], (3) Request changes [work.approve with decision: 'request_changes'], (4) Discuss [non-binding]. Both 1 and 2 record work.approve selected_number 1; they differ only in whether you then proceed to work.authorize. Never deny the human the choice to approve the spec without yet greenlighting implementation. When the human picks (3) Request changes, you MUST ALSO ask whether they want a re-review of the changes and pass it as re_review_required (work.approve rejects request_changes without it): true = after you edit, a fresh whole-WP review (work.review) is required before re-approval; false = the human waives re-review and the next approval skips the stale-review check. Don't decide this for them — it's the human's call.",
  "COMPUTE-DON'T-DEMAND: do not compute, guess, or hand-author values the tool derives — you supply intent, the tool supplies the derived artifact. content_hash (source_artifact.register), evidence_hash (source-derived ACs), and choice option_details are computed/derived for you: pass a placeholder (e.g. 64 zeros) or omit them entirely; the tool fills the canonical value and IGNORES a wrong one, so never re-bind, re-hash, or retry over a 'hash/shape mismatch'. The ONLY hashes you supply are review-snapshot tokens.",
  "For the whole-WP gates (work.approve / work.authorize / work.complete) echo back the current whole-Work-Packet hash as review_snapshot_hash. Get it from work.get, which returns the packet + its current approval_hash (non-mutating; use it any time, especially a fresh session). EVERY mutation response ALSO returns the FRESH approval_hash + a compact work_packet_summary (NOT the full document — call work.get when you need the detail), so chain the gates (approve -> authorize -> complete) using the hash from the previous response without a separate work.get. The action recomputes the hash itself and rejects a stale one — if it reports stale, a Spec changed since you reviewed, so work.get the fresh hash and pass it. Editing ANY Spec re-stales the whole-WP approval -> re-approve the whole packet. Use work.list to enumerate packets.",
  "When a Spec ESTABLISHES new architecture or stack (a greenfield app/API surface under new_entirely, OR a new app added to an existing repo under new_in_existing), its acceptance criteria MUST include at least one BOOTSTRAP acceptance criterion marked bootstrap: true covering standing up the repo/scaffold/runtime — not only leaf-feature ACs. The bulk approval is blocked (BOOTSTRAP_ACS_MISSING) until every establishing Spec has one. Inherited (modify_existing) work requires none. ADDITIONALLY, when the new target is an APP on a real-dev-runtime platform (web/desktop/mobile), the app Spec's implementation_plan (work.spec.plan) MUST carry a dev_runtime_proof: { command, readiness_assertion } — the dev-runtime command you will run + WHAT the readiness probe asserts on success (the meaning of 'the runtime works', e.g. 'loads the Todo UI and a created todo round-trips through the authenticated data path and persists across reload'). The bulk approval is blocked (DEV_RUNTIME_PROOF_PLAN_REQUIRED) until one Spec declares it. The proof RUNS as bootstrap work after authorization (the scaffold must exist first); its DESIGN is human-reviewed at the bulk approval so a hollow 'the server started' probe is caught up front — make the assertion cross the real process/auth/data seam, not just 'the process boots'.",
  "PER Spec, do implementation planning BEFORE the whole-WP review + the bulk approval: set the Spec's implementation plan with work.spec.plan (a standard_plan — summary + approach + expected_files + tests — or plan_waived_noop with a human exception). A standard_plan's expected_files must forecast the COMPLETE footprint: the implementation files, the TEST files (PLAN_EXPECTED_TEST_FILE_MISSING), and — when the Spec's docs policy requires docs — the DOC files (PLAN_EXPECTED_DOC_FILE_MISSING), not only the implementation files. The bulk approval is BLOCKED (IMPLEMENTATION_PLAN_REQUIRED) until EVERY Spec has a plan, and work.review REFUSES to run until every Spec is drafted (SPEC_REVIEW_DRAFT_INCOMPLETE) AND planned (IMPLEMENTATION_PLAN_REQUIRED) — the whole-WP review covers the ACs AND the implementation plans across ALL Specs, so never spawn the reviewer before every Spec is planned. The plan is in the whole-WP approval hash, so re-planning after approval re-stales it.",
  "work.spec.plan REQUIRES a `dependencies` declaration (no default — the call bounces without it; pass an explicit empty list when there are none). Per Spec, identify the cross-Spec EDGES it depends on: spec_dependencies = [{ spec_id, contract, reason }] where `contract` is an OPTIONAL PIN to the producer's frozen contract (a ContractRef { id, content_hash }), or null to derive it from the producer Spec. To depend on a contract from ANOTHER Work Packet (or a pre-existing one — the whole point of contracts being first-class), use contract_dependencies = [{ contract: { id, content_hash }, reason }]: Spec Guard resolves the pin against the cross-packet committed contract registry (CONTRACT_DEP_UNKNOWN if that frozen version isn't in the registry). Re-versioning a contract KEEPS prior versions, so a consumer pinned to an older hash is never broken by a producer's new version. (See the contract rule: the producer freezes a typed SURFACE that Spec Guard owns; consumers — in this packet or future ones — pin a frozen version of it.) `external_dependencies` (packages / existing modules) are informational only — the deterministic validator (build/typecheck) is their export authority, so they are ungated. Spec Guard gates the EDGE: each spec edge must resolve to a real sibling Spec (DEPENDENCY_SELF / DEPENDENCY_SPEC_UNKNOWN at plan time) and the whole graph must be ACYCLIC (DEPENDENCY_CYCLE at work.review — a cycle is a design smell: make it one Spec, or extract a shared-contract Spec). The build verifies the real exports; the reviewer judges whether the declared deps are TRUE (a false 'none' is caught where a plan describes using a sibling it never declared). work.review returns the topological implementation_order.",
  "Contract producers — the rest_api / reusable_api / reusable_ui classifications — MUST FREEZE a typed SURFACE at work.spec.plan via `contract_surface`: a hard JSON-Schema of the operations/procedures + their input/output types (REST ≈ OpenAPI; a tRPC/reusable_api = a procedure list + JSON Schema; reusable_ui = component prop-types as JSON Schema). Name the contract with `contract_id` for a readable registry id (e.g. 'todo-app-api'); it defaults to the Spec id. Spec Guard OWNS it — registers + content-hashes it into the COMMITTED, VERSIONED contract registry (.spec-guard/contracts/) and Spec.contract becomes a ref { id, content_hash }. CONTRACT_REQUIRED bounces a contract-producing plan without a surface. The surface is BOUND INTO APPROVAL, so the independent reviewer + the human review the INTERFACE itself (not prose), and editing it re-stales approval. Author the REAL hard schema — do NOT write prose; a prose 'contract' is just docs. Behavioral guarantees (empty-text rejection, not-found) stay in the ACs + tests, NOT the schema. A consumer pins the producer's frozen contract; CONTRACT_EDGE_MISMATCH (work.review) if the pin is stale/wrong; CONTRACT_NOT_READY (work.spec.record) if a depended-on contract isn't frozen in the registry. Because the contract is frozen AT PLAN, consumers are unblocked from authorization — there is NO freeze-during-implementation dance; work.get's `ready_in_parallel` is everything, so SPAWN THE IMPLEMENTERS CONCURRENTLY. Conformance of the code/docs/typed-mirror to the frozen schema is REVIEW-soft (the reviewer catches drift, like the docs requirement) + the whole-WP build; deterministic schema-vs-code extraction is a later phase.",
  "The breakdown IS the embedded Specs — there is NO separate Plan artifact, no plan.propose/establish, no child packets, no per-child approval. A fresh packet is one Spec; if it spans multiple surfaces, work.decompose it into >=2 classification-homogeneous Specs BEFORE the bulk approval. Every Spec is approved together in the ONE whole-WP gate, authorized together, and each carries its own ACs/docs/scope/implementation.",
  "TAG each acceptance criterion with its work CLASSIFICATION (its surface): reusable_api/rest_api for an API/contract surface, reusable_ui/one_off_application_ui for UI, direct_behavior for app logic, operational_document for docs. A Spec must be classification-HOMOGENEOUS — ACs of different classifications belong in SEPARATE Specs (work.decompose). So a multi-surface packet — e.g. an RPC API + a UI — MUST decompose into a reusable_api Spec and a one_off_application_ui Spec, each with its own docs/architecture policy (a reusable_api Spec requires API docs; a one_off_application_ui Spec does not). NEVER fold an API/contract surface into a UI Spec — that silently skips its docs + architecture requirements.",
  "INDEPENDENT pre-approval review — runnable IN PARALLEL per Spec. Before the bulk approval EVERY Spec must be covered by a passing independent review. You can review Specs CONCURRENTLY: call work.review with a `spec_id` per Spec and spawn a SEPARATE reviewer agent for each, in parallel (work.get returns `specs_awaiting_review` — the Specs ready to review now: this Spec + its dependencies drafted+planned) — and/or do ONE whole-WP review (work.review, NO spec_id) covering all Specs. Spawn reviewers at the CONFIGURED reviewer model (the reviewer role's tier — high_judgment resolves to claude-opus-4-8): set your subagent/Task tool's model parameter EXPLICITLY — do NOT rely on the coordinator's inherited model — and set producer.model to the model you ACTUALLY used (REVIEWER_MODEL_BELOW_CONFIGURED_TIER). A per-Spec reviewer reads ONE Spec (its ACs + classification + scope + plan + dependency edges); the whole-WP coherence reviewer reads ALL Specs TOGETHER to judge how they fit (synergize, not step on each other). Every review records each covered Spec's LOCAL content hash. TWO requirements at the approval gate: (1) per-Spec QUALITY — every Spec covered by a passing review at its CURRENT content, else SPEC_REVIEW_REQUIRED (unreviewed) or SPEC_REVIEW_STALE (edited since its review — re-review only THAT Spec; the others stay covered); (2) for a MULTI-Spec packet a WHOLE-WP COHERENCE review (NO spec_id, over ALL Specs, independent of EVERY author) bound to the current content — SPEC_REVIEW_COHERENCE_REQUIRED — because per-Spec reviewers each see one Spec and can't catch two unconnected Specs that conflict. A container edit (intent/stack) re-stales only the coherence review, not per-Spec coverage. work.review REFUSES until the Spec (and its dependencies) are drafted (SPEC_REVIEW_DRAFT_INCOMPLETE / SPEC_REVIEW_NOT_READY) and planned (IMPLEMENTATION_PLAN_REQUIRED). Independence: a per-Spec review must differ from THAT Spec's author; the coherence review from EVERY author (set work.spec.acs author_agent_instance_id; SPEC_SELF_REVIEW_BLOCKED). CRITICAL — a different agent_instance_id is NOT independence: you must ACTUALLY spawn separate reviewer agents (own context + reasoning, via your subagent/Task tool). A relabeled self-review is a violation; Spec Guard cannot verify a separate agent ran, so it marks independence 'asserted' — report it honestly, NEVER as 'independent'.",
  "For UI Specs (reusable_ui, one_off_application_ui) the FIRST feature question to the human is whether THEY have a mockup/design reference — do NOT ask 'what features do you want'. Resolve it BEFORE drafting any ACs and record it with work.spec.mockup — which REQUIRES the same human-confirmation contract as work.choice: human_confirmed: true + raw_response (the human's ACTUAL answer) + decision_prompt. You CANNOT set 'none' (or 'present') on the human's behalf — work.spec.mockup REJECTS it without confirmation (WORK_SPEC_MOCKUP_UNCONFIRMED). Ask the human, record their response. work.spec.acs (drafting ACs) is BLOCKED for a UI Spec until you do (MOCKUP_DECISION_REQUIRED) — so you literally CANNOT present a 'which features do you want' selection, or invent a feature set, before the human answers the mockup question. 'present' means the HUMAN already has a mockup: ASK them to provide it (a file path you can read, or paste/attach) and register THAT artifact with source_artifact.register — you MUST NOT create, generate, or design a mockup yourself; otherwise the answer is 'none'. For 'present', derive the ACs FROM the mockup as source_derived (source_evidence.kind any mockup/design term); the evidence_hash is computed for you, so pass a placeholder (e.g. 64 zeros) — do not mislabel mockup-derived ACs as human. For 'none', YOU draft the features from the goal and the human approves them at the bulk approval.",
  "For app/UI product platforms (web_app, desktop_app, mobile_app) the runtime baseline MUST establish a real dev runtime in runtime_development (a process group of one or more long-running processes plus a readiness_probe that, when multi-process, crosses the process seam — e.g. loads the UI AND hits the backend), proven by baseline.dev_runtime.run. It cannot be N/A'd and is not the production-serve command. ORIGINATION-AWARE: for new_entirely (greenfield) the dev runtime can only be proven once the scaffold exists, so it is ESTABLISHED + PROVEN as bootstrap work AFTER authorization (you must NOT write product code before authorization) and is enforced at the completion gate — work.complete blocks (COMPLETION_RUNTIME_BASELINE_REQUIRED) until an accepted, proven baseline exists. Accept the baseline DETERMINISTICALLY via baseline.establish once baseline.dev_runtime.run passes — there is NO separate human baseline-acceptance gate (the proof is deterministic; the human's judgment is at packet approval and work.complete). For modify_existing the dev runtime is INHERITED from the project's already-proven singleton baseline and never re-chosen. Backend/CLI/library platforms may mark runtime_development not-applicable.",
  "The work ends at the whole-WP human completion gate (work.complete): once EVERY Spec is review_complete, present 'Mark this Work Packet complete? (1) Yes / (2) No / (3) Discuss'. Deterministic completion readiness is enforced first (greenfield bootstrap cannot complete until its runtime baseline is proven); (2) No routes EVERY Spec back to review_blocked for rework; (3) Discuss is non-mutating. You never vouch for 'it runs' or 'tests pass' (those are deterministic) — you give the human's final acceptance.",
  "COMMITTABLE RECORD: the Work Packet lives as ONE canonical-JSON document at .spec-guard/packets/<id>.json, committed to git so the approved spec (intent + ACs + structural decisions + per-Spec content + the proof-of-approval stamp on lifecycle.*) travels with the code and a fresh session reads it instead of re-deriving. The rest of .spec-guard/ is a gitignored working store. Gate decisions (approve/authorize/complete/choice) are also appended to the decision log (decision.get/list).",
  "Documentation itself is never tested and retained docs tests must be removed.",
  "Tests must clean up files, data, processes, external resources, and runtime state.",
  "Backend roles run under harness-enforced permissions: coordinator/reviewer/validator cannot edit product code, self-review is blocked by default, and the validator decides pass/fail deterministically (no model decides pass/fail). The edit gate (a Claude PreToolUse hook in .claude/settings.json) enforces this: product code under a Spec's scope may be edited ONLY by a delegated spec-guard-implementer/fixer subagent; a coordinator/main-session edit is DENIED (exit 2) with a message to spawn the implementer. On Codex (whose PreToolUse carries no agent identity) SubagentStart/Stop maintain an edit lease the hook reads, so the same wall holds. Delegate Spec-scoped edits to the implementer subagent — do not write product code inline.",
  "DELEGATE the per-Spec role loop — do NOT run it inline as the coordinator wearing hats. After authorization, spawn a SEPARATE implementer agent per Spec to write the code against the approved Spec (it reads the ACs + implementation plan straight from Spec Guard, so it needs almost no briefing), and a SEPARATE reviewer agent. The coordinator does NOT implement, run tests, or debug inline: that churn (and the verbose test output) belongs in a disposable subagent so it never bloats the coordinator's long-lived context. Run the validator's commands through the deterministic command action (which keeps the output out of your context), never a raw shell call in the coordinator. Cost-match per the role config: spec-pinned execution (implement/fix) and semantic review run on the cheaper 'standard' tier, mechanical verification needs no model, and the premium coordinator stays on governance + the human gates only.",
  "The reviewer is ALWAYS a different agent than whoever wrote the code — self-review is never valid. The role config defaults to strict identity, so config.check reports self_review_viable: false until a genuinely separate reviewer agent exists; reviewing your own implementation removes the only point of review (independent eyes).",
  "ENFORCED, not just advised: work.spec.record REJECTS an implementation_attempt whose producer role is not edit-capable or runs inline (LOOP_IMPLEMENTATION_NOT_DELEGATED / LOOP_INLINE_MECHANICAL_WORK_BLOCKED), and REJECTS a review_cycle whose reviewer identity matches the implementer of the attempt under review (LOOP_SELF_REVIEW_BLOCKED). Each lineage record's `producer` must honestly report the role + agent_instance_id of the agent that did the work — the coordinator recording its own inline implementation or review will not advance the Spec, and work.spec.advance CANNOT skip these record-gated transitions. The `execution` field (inline vs subagent) makes the firewall explicit; only the coordinator is inline.",
  "work.spec.record takes your SIMPLE report, NOT a hand-built lineage record. Pass record_kind + next_state + a small `record`: implementation_attempt = { producer, summary, changed_files } (changed_files must be HONEST — see the evidence rule); review_cycle = { producer, verdict (pass/blocked), summary, blockers?, evidence_satisfaction? } (binds to the Spec's latest sealed attempt; evidence_satisfaction proves the ACs — see the evidence rule); fix_instruction = { producer, source_review_cycle_id?, blocker_ids?, allowed_files?, constraints? }. The tool SYNTHESIZES + SEALS the full record for you — the ids, the hashes (incl. the REAL working-tree footprint), the authorization linkage. NEVER hand-author hashes, `state: \"sealed\"`, or the internal record shape, and never probe the schema with rejected calls to reverse-engineer it: that is the compute-don't-demand failure — supply intent, the tool supplies the derived artifact. Spawn the implementer/fixer subagent at the CONFIGURED edit-role tier (high_judgment -> claude-opus-4-8) — code quality degrades sharply on a cheaper model; set your subagent/Task tool's model parameter EXPLICITLY (do NOT rely on the coordinator's inherited model) and report the model you used in producer.model. work.spec.record flags a below-tier implementation (IMPLEMENTATION_MODEL_BELOW_CONFIGURED_TIER).",
  "EVIDENCE + the completion backstop (per-Spec accountability, ENFORCED at work.complete). (1) HONEST footprint: an implementation_attempt's changed_files must match reality — Spec Guard diffs the real working tree against the authorize baseline (manifest, or git diff vs the baseline commit so a mid-loop commit can't hide it) and WARNS (FOOTPRINT_REPORTED_MISMATCH) when your report disagrees with the in-scope diff. (2) PROVE every AC: at the per-Spec review (work.spec.record review_cycle) the reviewer records evidence_satisfaction = [{ ac_id, satisfied, mode, evidence_refs, notes }] — every NON-bootstrap AC must have a satisfied entry on the LATEST review cycle or work.complete blocks (COMPLETION_AC_UNPROVEN). A BEHAVIORAL AC's evidence is a PASSED test: run that specific test via command.run and put its 'command-result:<id>' ref in evidence_refs — work.complete RESOLVES it and blocks if it isn't 'passed' (COMPLETION_AC_EVIDENCE_NOT_PASSED), so it's a real passed test, not a claim. (3) NO unrecorded changes: work.complete runs an un-bendable backstop — any product file under a Spec's scope that changed with NO recorded implementation_attempt covering it blocks (COMPLETION_UNRECORDED_CHANGES), even if it compiles. EVERY change must go through a delegated implementer + work.spec.record — a coordinator that edits product code directly, or commits work it never recorded, cannot complete. (A Spec's scope is its allowed_globs, or, if none was declared, derived from the plan's expected_files.) The whole-WP build is also re-run at completion (COMPLETION_VALIDATION_FAILED) — the final code must COMPILE."
];

function agentGuide(): string {
  return `# Spec Guard Agent Guide\n\nStart with the generated Pi/MCP tools, not package internals.\n\n## Rules\n\n${AGENT_GUIDE_RULES.map((rule) => `- ${rule}`).join("\n")}\n\n## Recommended first tool calls\n\n- spec_guard_mcp_status\n- spec_guard_mcp_quickstart\n- spec_guard_config_check\n`;
}

function quickstartMarkdown(): string {
  return `# Spec Guard MCP/Pi Quickstart\n\n1. Reload/restart Pi so .pi/extensions/spec-guard.ts is discovered.\n2. Reload/approve MCP clients after reviewing the generated config; they launch the locally-installed Spec Guard server via \`npx spec-guard-mcp\`. (MCP servers are loaded at client start and need one-time approval, so this is a manual step the agent cannot self-serve.)\n3. First call spec_guard_mcp_status, spec_guard_mcp_quickstart, or spec_guard_config_check.\n4. Use Spec Guard tools directly; CLI is for bootstrap/init only unless a local runtime command is explicitly documented.\n5. Human-confirmed fields require actual human responses and numbered selections; preserve Discuss semantics.\n\n${AGENT_GUIDE_RULES.map((rule) => `- ${rule}`).join("\n")}\n`;
}

function matrixMarkdown(): string {
  return `# Spec Guard Client Support Matrix\n\nMCP clients launch the locally-installed server via \`npx spec-guard-mcp\` (npx resolves node_modules/.bin first; no registry package is required).\n\n| Client | Generated file | Server |\n|---|---|---|\n| Generic MCP | .mcp.json | npx spec-guard-mcp stdio server |\n| Cursor | .cursor/mcp.json | npx spec-guard-mcp stdio server |\n| VS Code | .vscode/mcp.json | npx spec-guard-mcp stdio server |\n| Cline | .cline/mcp.json, .cline/cline_mcp_settings.json | npx spec-guard-mcp stdio server |\n| Roo | .roo/mcp.json, .roo/roo_mcp_settings.json | npx spec-guard-mcp stdio server |\n| Windsurf | .windsurf/mcp.json, .windsurf/mcp_config.json | npx spec-guard-mcp stdio server |\n| Pi | .pi/extensions/spec-guard.ts | Direct registry-parity tools |\n`;
}

function piExtensionMarkdown(): string {
  return `# Spec Guard Pi Extension\n\nProject-local extension: .pi/extensions/spec-guard.ts\n\nReload or restart Pi after init. The extension default-exports a factory and registers spec_guard_* tools directly. Call spec_guard_mcp_status or spec_guard_mcp_quickstart first.\n`;
}

export async function generateHarnessFiles(projectRoot: string, artifactRoot: string): Promise<GeneratedFileResult[]> {
  const artifactRootAbs = path.isAbsolute(artifactRoot) ? artifactRoot : path.join(projectRoot, artifactRoot);
  const projectFiles: Array<[string, string]> = [
    [".mcp.json", mcpConfigJson()],
    [".cursor/mcp.json", mcpConfigJson()],
    [".vscode/mcp.json", mcpConfigJson()],
    [".cline/mcp.json", mcpConfigJson()],
    [".cline/cline_mcp_settings.json", mcpConfigJson()],
    [".roo/mcp.json", mcpConfigJson()],
    [".roo/roo_mcp_settings.json", mcpConfigJson()],
    [".windsurf/mcp.json", mcpConfigJson()],
    [".windsurf/mcp_config.json", mcpConfigJson()],
    [".pi/extensions/spec-guard.ts", renderPiExtension({ projectRoot, artifactRoot })],
    ["SPEC_GUARD_AGENT_GUIDE.md", agentGuide()]
  ];
  const harnessFiles: Array<[string, string]> = [
    ["claude-desktop-snippet.json", genericSnippetJson()],
    ["pi-extension.md", piExtensionMarkdown()],
    ["mcp-quickstart.md", quickstartMarkdown()],
    ["client-support-matrix.md", matrixMarkdown()],
    ["generic-stdio-snippet.json", genericSnippetJson()]
  ];

  const results: GeneratedFileResult[] = [];
  for (const [relativePath, content] of projectFiles) {
    results.push(await writeGeneratedFile(path.join(projectRoot, relativePath), relativePath, content));
  }
  for (const [fileName, content] of harnessFiles) {
    const absolutePath = path.join(artifactRootAbs, "harness", fileName);
    const reportedPath = path.isAbsolute(artifactRoot) ? absolutePath : path.join(artifactRoot, "harness", fileName);
    results.push(await writeGeneratedFile(absolutePath, reportedPath, content));
  }
  return results;
}
